version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=${DB_URL}
      - ADMIN_KEY=${ADMIN_KEY}
      - AI_SERVICE_KEY=${AI_SERVICE_KEY}
    restart: always

  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    environment:
      - AI_SERVICE_KEY=${AI_SERVICE_KEY}
      - RPC_URLS=${RPC_URLS}
    restart: always

volumes:
  postgres_data:
